import Web3 from "web3"
import { readFileSync } from "fs"

let ganache
try {
    // `gen/ganache.json` generated by `npm run ganache` see package.json
    ganache = JSON.parse(readFileSync(`gen/ganache.json`))
} catch(e) {
    ganache = {}
}

// available private keys generated by `npm run ganache` see package.json
/**
 * 0xbbccc72adbf3116f8112b73c18378a633eef2c619d17252609349195e3e725ae 100ETH
 * 0xddf8298ba2408b9cd4057dca845161b3d66b040832f609dd45076daba14deca8 100ETH"
 */
const privateKeys = Object.keys(ganache.private_keys)
    .map(e => ganache.private_keys[e])
    .map(e => `0x${e}`)

// define our local network
export const web3 = new Web3(`http://localhost:8545`)
export const account = web3.eth.accounts.privateKeyToAccount(privateKeys[0])
export const secondAccount = web3.eth.accounts.privateKeyToAccount(privateKeys[1])

// networkGas default from `ganache-cli --help`
export const networkGas = 6721975